# Generated by Django 2.0 on 2017-12-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flying', '0002_auto_20171226_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=75, primary_key=True, serialize=False),
        ),
    ]
