# Generated by Django 2.0 on 2017-12-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flying', '0003_auto_20171226_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='airlineID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Flying.Airline'),
        ),
        migrations.AlterField(
            model_name='route',
            name='dAirportID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Flying.Airport'),
        ),
        migrations.AlterField(
            model_name='route',
            name='sAirportID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Flying.Airport'),
        ),
    ]
